# Generated by Django 5.1.7 on 2025-09-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_zip_code_address_zipcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='postal_code',
        ),
    ]
