# Generated by Django 5.1.7 on 2025-08-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
